# Generated by Django 3.1.7 on 2021-08-30 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod1', models.CharField(choices=[('Mobile', 'Mobile'), ('Tablet', 'Tablet'), ('Desktop', 'Desktop'), ('Laptop', 'Laptop')], max_length=40)),
                ('Name', models.CharField(max_length=40)),
                ('screensize', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('price', models.FloatField(default=0.0)),
                ('brand', models.CharField(max_length=40)),
                ('description', models.TextField(null=True, verbose_name='TYPE YOUR DESCRIPTION')),
                ('quantity', models.IntegerField(default=0)),
                ('battery', models.CharField(default='None', max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('image', models.ImageField(default='media/mobile/images/default_m.jpg', upload_to='media/mobile/images')),
                ('dealerQuantity', models.IntegerField(default=1)),
                ('delivery', models.IntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('display', models.CharField(default='HD', max_length=20)),
                ('frontCamera', models.IntegerField()),
                ('rearCamera', models.IntegerField()),
                ('waterproof', models.BooleanField(default=False)),
                ('goodies', models.CharField(default='Guide', max_length=50)),
                ('Refurbished', models.BooleanField(default=False)),
                ('os', models.CharField(default='Android', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5)),
                ('location', models.TextField(default='India')),
                ('contact', models.CharField(default='+91', max_length=13)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prod', models.ManyToManyField(null=True, related_name='prod', to='Products.Product1')),
            ],
        ),
    ]
